# Sprites
BACKGROUND_PNG = "sprites/background.png"
WALL_BLOCK_SPRITE = "sprites/wall_block.png"
PLATFORM_START = "sprites/platform_start.png"
PLATFORM_MIDDLE = "sprites/platform_middle.png"

# Sizes
GAME_WIDTH = 600
GAME_HEIGHT = 600
WALL_BLOCK_WIDTH = 46
WALL_BLOCK_HEIGHT = 58
PLATFORM_ELEMENT_WIDTH = 16
PLATFORM_ELEMENT_HEIGHT = 32

# Player
VERTICAL_ACCELERATION_STARTING_VALUE = 16
VERTICAL_ACCELERATION_CHANGE_VALUE = 0.5
HORIZONTAL_ACCELERATION_VALUE = 0.5
HORIZONTAL_ACCELERATION_MIN = -3 * HORIZONTAL_ACCELERATION_VALUE
HORIZONTAL_ACCELERATION_MAX = 3 * HORIZONTAL_ACCELERATION_VALUE
HORIZONTAL_ACCELERATION_UPPER_LIMIT = 20 * HORIZONTAL_ACCELERATION_VALUE
HORIZONTAL_ACCELERATION_LOWER_LIMIT = -1 * HORIZONTAL_ACCELERATION_UPPER_LIMIT
GRAVITY_VALUE = 3

# PLATFORM
BASE_PLATFORM_SPEED = 1.0
